name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no bitnami@13.239.234.32 << 'EOF'
            cd /opt/bitnami/wordpress/wp-content/themes/your-child-theme-name
            git pull origin main
            sudo chown -R bitnami:daemon .
          EOF
